### ISSUE TITLE
Estimate gas refund

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxdao-contracts#76]
<img width="533" alt="Screenshot 2022-02-28 at 16 26 39" src="https://user-images.githubusercontent.com/39137239/156081460-c2c766d8-e944-45b8-b2f5-5d92b044cdea.png">

**Comment by AugustoL** [comment]
This issue wont be addressed since it can be exploited by a user to spend unnecessary gas on a proposal execution, the gas refund should always be controlled by the dao, having a fix refund might not be ideal but considering that there is no dao addressing this issue I think any solution would be very good, later we can improve it on future voting machine versions, for now it would be a fixed amount of gas set by the dao.
